# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1713, 1408)
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 19, 1681, 1371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayoutMain = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayoutMain.setContentsMargins(0, 0, 0, 0)
        self.vLayoutMain.setObjectName("vLayoutMain")
        self.titleLabel = CaptionLabel(self.verticalLayoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.vLayoutMain.addWidget(self.titleLabel)
        self.horizLayoutTop = QtWidgets.QHBoxLayout()
        self.horizLayoutTop.setSpacing(80)
        self.horizLayoutTop.setObjectName("horizLayoutTop")
        self.searchLine = SearchLineEdit(self.verticalLayoutWidget)
        self.searchLine.setObjectName("searchLine")
        self.horizLayoutTop.addWidget(self.searchLine)
        self.searchProgressRing = IndeterminateProgressRing(self.verticalLayoutWidget)
        self.searchProgressRing.setObjectName("searchProgressRing")
        self.horizLayoutTop.addWidget(self.searchProgressRing)
        self.legacySwitchButton = SwitchButton(self.verticalLayoutWidget)
        self.legacySwitchButton.setObjectName("legacySwitchButton")
        self.horizLayoutTop.addWidget(self.legacySwitchButton)
        self.vLayoutMain.addLayout(self.horizLayoutTop)
        self.resultTable = TableView(self.verticalLayoutWidget)
        self.resultTable.setObjectName("resultTable")
        self.vLayoutMain.addWidget(self.resultTable)
        self.horizLayoutBottom = QtWidgets.QHBoxLayout()
        self.horizLayoutBottom.setObjectName("horizLayoutBottom")
        self.detailImageLabel = ImageLabel(self.verticalLayoutWidget)
        self.detailImageLabel.setObjectName("detailImageLabel")
        self.horizLayoutBottom.addWidget(self.detailImageLabel)
        self.detailLabel = BodyLabel(self.verticalLayoutWidget)
        self.detailLabel.setObjectName("detailLabel")
        self.horizLayoutBottom.addWidget(self.detailLabel)
        self.downloadButton = PushButton(self.verticalLayoutWidget)
        self.downloadButton.setObjectName("downloadButton")
        self.horizLayoutBottom.addWidget(self.downloadButton)
        self.vLayoutMain.addLayout(self.horizLayoutBottom)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.titleLabel.setText(_translate("Frame", "Caption label"))
        self.detailLabel.setText(_translate("Frame", "Body label"))
        self.downloadButton.setText(_translate("Frame", "Push button"))
from qfluentwidgets import BodyLabel, CaptionLabel, ImageLabel, IndeterminateProgressRing, PushButton, SearchLineEdit, SwitchButton, TableView
